use std::error::Error;

fn main() -> Result<(), Box<dyn Error>>{
    //let data = get_daily_input(25,2024)?;
    
    Ok(())
}



#[cfg(test)]
mod tests {
    

    #[test]
    fn test_part1() {
        
    }

    #[test]
    fn test_part2() {
    }
}